baseURL = "https://wiki.brisberg.dev/"
languageCode = "en-us"
title = "Brisberg Wiki"
theme = "Book"

# Theme configuration
# See https://github.com/alex-shpak/hugo-book#configuration for documentation

# Book configuration
disablePathToLower = false
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
[[menu.after]]
  name = "Blog"
  url = "https://blog.brisberg.dev"
  weight = 9
[[menu.after]]
  name = "Github"
  url = "https://github.com/brisberg/wiki.brisberg.dev"
  weight = 10

[params]
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'

  # Show table of contents on right side of pages.
  BookToC = true

  # Path to logo asset. Relative under '/static/'.
  BookLogo = 'favicon.png'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/brisberg/wiki.brisberg.dev'

  # Enable "Edit this page" links for 'doc' page type.
  BookEditPath = 'edit/main/site'

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = 'January 2, 2006'

  # Enables search function with flexsearch,
  # Configuration for indexing can be adjusted in i18n folder per language.
  BookSearch = true

  # Disables comments template on pages
  # See https://gohugo.io/content-management/comments/#configure-disqus
  BookComments = false

  # /!\ This is an experimental feature, might be removed or changed at any time
  # Enables service worker that caches visited pages and resources for offline use.
  BookServiceWorker = true
