[[main]]
  identifier = "home"
  name = "Home"
  url = "https://brisberg.dev"
  weight = 1

[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 2

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 3
